input:
  master:
    file: ./test/input.csv
    summaryMatchColumns:
      - Business Name
  summaryData:
    folder: ./test/input-csvs/
    column: Review Text
prompt: Summarise the following reviews.
output:
  file: ./test/output.csv
  headers: Business Name,Review
  column: Review Summary
