input:
  master:
    file: ./input/Soft Plays v2.0 Example.csv
    summaryMatchColumns:
      - Name
      - Fulladdress
  summaryData:
    folder: ./input/Business Reviews/
    column: Review Text
prompt: Summarise the following reviews.
output:
  file: ./output/Master with Review Summaries.csv
  headers: Business Name,Review
  column: Review Summary
